### ISSUE TITLE
Producer.OnError should be subscribed to

### ISSUE THREAD

**Issue by martinosk** [dfds/capability-service#1]
If errors occurs in 
`var result = await producer.ProduceAsync(
                            topic: topicName,
                            key: evt.AggregateId,
                            val: message
                        );`
it may block indefinately.
producer.OnError event should be subscribed to so that errors can be logged and handled gracefully.

To reproduce: Change bootstrap.servers to an invalid host and run produer.ProduceAsync
 
[PublishingService](https://github.com/dfds/capability-service/blob/master/src/CapabilityService.WebApi/Infrastructure/Messaging/PublishingService.cs)

**Comment by kim-lindhard-dfds** [comment]
Thank you for the insight we will add it to our backlog and keep it in mind when writing other producers in the future.

**Comment by janwiberg-dfds** [comment]
This was apparently fixed a while ago but we forgot to close this issue. Sorry.
