### ISSUE TITLE
Multiple producers of events with >1 replicas

### ISSUE THREAD

**Issue by wcarlsen** [dfds/capability-service#100]
When using the outbox pattern we need to avoid having multiple event producers of the same event.

![image](https://user-images.githubusercontent.com/17003032/79232677-1d360700-7e68-11ea-96c3-102fd8d5ab60.png)

**Comment by kim-lindhard-dfds** [comment]
Aha found a piece of the capability service that doesn't scale

**Comment by wcarlsen** [comment]
@SEQUOIIA I guess this service still doesn't scale?
