### ISSUE TITLE
Does not recognise me as joined to capabilities I am member of

### ISSUE THREAD

**Issue by abstrask** [dfds/capability-service#33]
**Describe the bug**
Looking at https://build.dfds.cloud/capabilities, I (raras@dfds.com) appeared to have only joined one capability; DED-Infrastructure. However, I was also member of:

- Smartdata-ats
- X-Smartdata-ats

Clicking on each of these capabilties, my username was listed a member, but I had the option to join, rather than leave.

![image](https://user-images.githubusercontent.com/10578276/63688252-20ac4d80-c807-11e9-9417-9aa2744ac0a1.png)

I since clicked "Join" on the X-Smartdata-ats capability, which caused my username to appear twice (one of them highlighted as being me). Clicking  "Leave" afterwards seemed to remove both references to my username.

**Comment by wcarlsen** [comment]
We allow for Upper case emails being persisted in the DB

**Comment by avnes** [comment]
@SEQUOIIA - is this old bug still relevant?

**Comment by SEQUOIIA** [comment]
Unsure. @jandr-dfds or @thofisch might get around to test it at some point.

**Comment by thofisch** [comment]
@SEQUOIIA and @avnes Do we have any idea if this is affecting other users? Would be nice with a case concerning a currently employed member. Otherwise I'm all for closing the issue, if this is the only reported bug, as it's over 3 years old...
